version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    container_name: login-postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT:-7777}:7777"
    env_file:
      - ./.env
    command: ["make", "run"]

volumes:
  postgres_data: