version: "3.9"

services:
  go-geolocation:
    build: .
    container_name: go-geolocation-container
    restart: always
    env_file:
      - .env
    ports:
      - "7777:8080"
    volumes:
      - .:/app

  go-geolocation-dev:
    build: .
    container_name: go-geolocation-dev-container
    restart: always
    env_file:
      - .env.dev
    ports:
      - "7070:8080"
    volumes:
      - .:/app

  go-geolocation-homolog:
    build: .
    container_name: go-geolocation-homolog-container
    restart: always
    env_file:
      - .env.homolog
    ports:
      - "9089:8080"
    volumes:
      - .:/app

