version: "3.9"

services:
  api:
    build: .
    container_name: ${CONTAINER_NAME:-go-geolocation}
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - redis
    networks:
      - geo-network

  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_NAME_REDIS:-geo-redis}
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - geo-network

networks:
  geo-network:
    driver: bridge

volumes:
  redis_data:
