version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    container_name: login-postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
      image: sua-imagem-da-aplicacao
      ports:
        - "8080:8080"
      depends_on:
        - redis
      environment:
        - REDIS_URL=redis://redis:6379

      redis:
        image: redis:6
        ports:
          - "6379:6379"
        volumes:
          - /var/lib/redis:/data

volumes:
  postgres_data:
  redis_data:
