ALTER TABLE driver ADD COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE driver ADD COLUMN cep VARCHAR(8) NOT NULL;
ALTER TABLE driver ADD COLUMN complement VARCHAR(100);

ALTER TABLE tractor_unit ADD COLUMN state VARCHAR(30) NOT NULL;
ALTER TABLE tractor_unit ADD COLUMN renavan VARCHAR(11) NOT NULL;
ALTER TABLE tractor_unit ADD COLUMN capacity VARCHAR(100) NOT NULL;
ALTER TABLE tractor_unit ADD COLUMN width FLOAT NOT NULL;
ALTER TABLE tractor_unit ADD COLUMN length FLOAT NOT NULL;
ALTER TABLE tractor_unit ADD COLUMN color VARCHAR(50) NOT NULL;

ALTER TABLE trailer ADD COLUMN state VARCHAR(30) NOT NULL;
ALTER TABLE trailer ADD COLUMN renavan VARCHAR(11) NOT NULL;

ALTER TABLE advertisement DROP COLUMN cargo_volume;


