CREATE TABLE announcement (
                              id BIGSERIAL PRIMARY KEY,
                              destination VARCHAR(255) NOT NULL,
                              origin VARCHAR(255) NOT NULL,
                              destination_lat DECIMAL(10,6) NOT NULL,
                              destination_lng DECIMAL(10,6) NOT NULL,
                              origin_lat DECIMAL(10,6) NOT NULL,
                              origin_lng DECIMAL(10,6) NOT NULL,
                              description TEXT NOT NULL,
                              cargo_description TEXT NOT NULL,
                              payment_description TEXT NOT NULL,
                              delivery_date DATE NOT NULL,
                              pickup_date DATE NOT NULL,
                              deadline_date DATE NOT NULL,
                              price DECIMAL(10,2) NOT NULL,
                              vehicle VARCHAR(100) NOT NULL,
                              body_type VARCHAR(100) NOT NULL,
                              kilometers DECIMAL(10,2) NOT NULL,
                              cargo_nature VARCHAR(100) NOT NULL,
                              cargo_type VARCHAR(100) NOT NULL,
                              cargo_weight DECIMAL(10,2) NOT NULL,
                              tracking BOOLEAN NOT NULL,
                              requires_tarp BOOLEAN NOT NULL,
                              status BOOL NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              updated_at TIMESTAMP NULL
);
