// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balanca.sql

package db

import (
	"context"
)

const getBalanca = `-- name: GetBalanca :many
SELECT id, concessionaria, km, lat, lng, nome, rodovia, sentido, uf
FROM public.balanca
`

func (q *Queries) GetBalanca(ctx context.Context) ([]Balanca, error) {
	rows, err := q.db.QueryContext(ctx, getBalanca)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balanca
	for rows.Next() {
		var i Balanca
		if err := rows.Scan(
			&i.ID,
			&i.Concessionaria,
			&i.Km,
			&i.Lat,
			&i.Lng,
			&i.Nome,
			&i.Rodovia,
			&i.Sentido,
			&i.Uf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
