// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: chat_room.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createChatRoom = `-- name: CreateChatRoom :one

INSERT INTO chat_rooms
(id, advertisement_id, advertisement_user_id, interested_user_id, status, created_at)
VALUES
(nextval('chat_rooms_id_seq'::regclass), $1, $2, $3, true, now())
RETURNING id, advertisement_id, advertisement_user_id, interested_user_id, status, created_at, updated_at
`

type CreateChatRoomParams struct {
	AdvertisementID     int64 `json:"advertisement_id"`
	AdvertisementUserID int64 `json:"advertisement_user_id"`
	InterestedUserID    int64 `json:"interested_user_id"`
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatRoom, error) {
	row := q.db.QueryRowContext(ctx, createChatRoom, arg.AdvertisementID, arg.AdvertisementUserID, arg.InterestedUserID)
	var i ChatRoom
	err := row.Scan(
		&i.ID,
		&i.AdvertisementID,
		&i.AdvertisementUserID,
		&i.InterestedUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarrierChatRooms = `-- name: GetCarrierChatRooms :many
SELECT r.id, r.advertisement_id, r.advertisement_user_id, r.interested_user_id, r.status, r.created_at, r.updated_at, a.id as advertisement_id, a.origin, a.destination, a.distance FROM chat_rooms r
JOIN "advertisement" a ON a.id = r.advertisement_id
WHERE r.interested_user_id = $1
`

type GetCarrierChatRoomsRow struct {
	ID                  int64        `json:"id"`
	AdvertisementID     int64        `json:"advertisement_id"`
	AdvertisementUserID int64        `json:"advertisement_user_id"`
	InterestedUserID    int64        `json:"interested_user_id"`
	Status              bool         `json:"status"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
	AdvertisementID_2   int64        `json:"advertisement_id_2"`
	Origin              string       `json:"origin"`
	Destination         string       `json:"destination"`
	Distance            int64        `json:"distance"`
}

func (q *Queries) GetCarrierChatRooms(ctx context.Context, interestedUserID int64) ([]GetCarrierChatRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCarrierChatRooms, interestedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCarrierChatRoomsRow
	for rows.Next() {
		var i GetCarrierChatRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvertisementID,
			&i.AdvertisementUserID,
			&i.InterestedUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdvertisementID_2,
			&i.Origin,
			&i.Destination,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatRoomById = `-- name: GetChatRoomById :one
SELECT r.id, r.advertisement_id, r.advertisement_user_id, r.interested_user_id, r.status, r.created_at, r.updated_at, a.id as advertisement_id, a.origin, a.destination, a.distance FROM chat_rooms r
JOIN "advertisement" a ON a.id = r.advertisement_id
WHERE r.id = $1
`

type GetChatRoomByIdRow struct {
	ID                  int64        `json:"id"`
	AdvertisementID     int64        `json:"advertisement_id"`
	AdvertisementUserID int64        `json:"advertisement_user_id"`
	InterestedUserID    int64        `json:"interested_user_id"`
	Status              bool         `json:"status"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
	AdvertisementID_2   int64        `json:"advertisement_id_2"`
	Origin              string       `json:"origin"`
	Destination         string       `json:"destination"`
	Distance            int64        `json:"distance"`
}

func (q *Queries) GetChatRoomById(ctx context.Context, id int64) (GetChatRoomByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getChatRoomById, id)
	var i GetChatRoomByIdRow
	err := row.Scan(
		&i.ID,
		&i.AdvertisementID,
		&i.AdvertisementUserID,
		&i.InterestedUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdvertisementID_2,
		&i.Origin,
		&i.Destination,
		&i.Distance,
	)
	return i, err
}

const getDriverChatRooms = `-- name: GetDriverChatRooms :many
SELECT r.id, r.advertisement_id, r.advertisement_user_id, r.interested_user_id, r.status, r.created_at, r.updated_at, a.id as advertisement_id, a.origin, a.destination, a.distance FROM chat_rooms r
JOIN "advertisement" a ON a.id = r.advertisement_id
WHERE r.interested_user_id = $1
`

type GetDriverChatRoomsRow struct {
	ID                  int64        `json:"id"`
	AdvertisementID     int64        `json:"advertisement_id"`
	AdvertisementUserID int64        `json:"advertisement_user_id"`
	InterestedUserID    int64        `json:"interested_user_id"`
	Status              bool         `json:"status"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
	AdvertisementID_2   int64        `json:"advertisement_id_2"`
	Origin              string       `json:"origin"`
	Destination         string       `json:"destination"`
	Distance            int64        `json:"distance"`
}

func (q *Queries) GetDriverChatRooms(ctx context.Context, interestedUserID int64) ([]GetDriverChatRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDriverChatRooms, interestedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDriverChatRoomsRow
	for rows.Next() {
		var i GetDriverChatRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvertisementID,
			&i.AdvertisementUserID,
			&i.InterestedUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdvertisementID_2,
			&i.Origin,
			&i.Destination,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
