// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chat_message.sql

package db

import (
	"context"
	"database/sql"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages
(room_id, user_id, content, status, is_read)
VALUES
($1, $2, $3, true, false)
RETURNING id, room_id, user_id, content, status, reply_id, read_at, is_read, created_at, updated_at
`

type CreateChatMessageParams struct {
	RoomID  sql.NullInt64 `json:"room_id"`
	UserID  sql.NullInt64 `json:"user_id"`
	Content string        `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.RoomID, arg.UserID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.Status,
		&i.ReplyID,
		&i.ReadAt,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
