// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: driver.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO public.driver
(id, user_id, name, birth_date, cpf, license_number, license_category, license_expiration_date, state, city, neighborhood, street, street_number, phone, cep, complement, status, created_at)
VALUES(nextval('driver_id_seq'::regclass), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
       $12, $13, $14, $15,true, now())
    RETURNING id, user_id, birth_date, cpf, license_number, license_category, license_expiration_date, state, city, neighborhood, street, street_number, phone, status, created_at, updated_at, name, cep, complement
`

type CreateDriverParams struct {
	UserID                int64          `json:"user_id"`
	Name                  string         `json:"name"`
	BirthDate             time.Time      `json:"birth_date"`
	Cpf                   string         `json:"cpf"`
	LicenseNumber         string         `json:"license_number"`
	LicenseCategory       string         `json:"license_category"`
	LicenseExpirationDate time.Time      `json:"license_expiration_date"`
	State                 sql.NullString `json:"state"`
	City                  sql.NullString `json:"city"`
	Neighborhood          sql.NullString `json:"neighborhood"`
	Street                sql.NullString `json:"street"`
	StreetNumber          sql.NullString `json:"street_number"`
	Phone                 string         `json:"phone"`
	Cep                   string         `json:"cep"`
	Complement            sql.NullString `json:"complement"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, createDriver,
		arg.UserID,
		arg.Name,
		arg.BirthDate,
		arg.Cpf,
		arg.LicenseNumber,
		arg.LicenseCategory,
		arg.LicenseExpirationDate,
		arg.State,
		arg.City,
		arg.Neighborhood,
		arg.Street,
		arg.StreetNumber,
		arg.Phone,
		arg.Cep,
		arg.Complement,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.Cpf,
		&i.LicenseNumber,
		&i.LicenseCategory,
		&i.LicenseExpirationDate,
		&i.State,
		&i.City,
		&i.Neighborhood,
		&i.Street,
		&i.StreetNumber,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Cep,
		&i.Complement,
	)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
UPDATE public.driver
SET status=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteDriver(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDriver, id)
	return err
}

const getDriverById = `-- name: GetDriverById :one
SELECT id, user_id, birth_date, cpf, license_number, license_category, license_expiration_date, state, city, neighborhood, street, street_number, phone, status, created_at, updated_at, name, cep, complement
FROM public.driver
WHERE id=$1
`

func (q *Queries) GetDriverById(ctx context.Context, id int64) (Driver, error) {
	row := q.db.QueryRowContext(ctx, getDriverById, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.Cpf,
		&i.LicenseNumber,
		&i.LicenseCategory,
		&i.LicenseExpirationDate,
		&i.State,
		&i.City,
		&i.Neighborhood,
		&i.Street,
		&i.StreetNumber,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Cep,
		&i.Complement,
	)
	return i, err
}

const getDriverByUserId = `-- name: GetDriverByUserId :many
SELECT id, user_id, birth_date, cpf, license_number, license_category, license_expiration_date, state, city, neighborhood, street, street_number, phone, status, created_at, updated_at, name, cep, complement
FROM public.driver
WHERE user_id=$1
`

func (q *Queries) GetDriverByUserId(ctx context.Context, userID int64) ([]Driver, error) {
	rows, err := q.db.QueryContext(ctx, getDriverByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthDate,
			&i.Cpf,
			&i.LicenseNumber,
			&i.LicenseCategory,
			&i.LicenseExpirationDate,
			&i.State,
			&i.City,
			&i.Neighborhood,
			&i.Street,
			&i.StreetNumber,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Cep,
			&i.Complement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE public.driver
SET user_id=$2, birth_date=$3, license_category=$4, license_expiration_date=$5, state=$6, city=$7, neighborhood=$8, street=$9, street_number=$10, phone=$11, cep=$12, complement=$13, updated_at=now()
WHERE id=$1
    RETURNING id, user_id, birth_date, cpf, license_number, license_category, license_expiration_date, state, city, neighborhood, street, street_number, phone, status, created_at, updated_at, name, cep, complement
`

type UpdateDriverParams struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	BirthDate             time.Time      `json:"birth_date"`
	LicenseCategory       string         `json:"license_category"`
	LicenseExpirationDate time.Time      `json:"license_expiration_date"`
	State                 sql.NullString `json:"state"`
	City                  sql.NullString `json:"city"`
	Neighborhood          sql.NullString `json:"neighborhood"`
	Street                sql.NullString `json:"street"`
	StreetNumber          sql.NullString `json:"street_number"`
	Phone                 string         `json:"phone"`
	Cep                   string         `json:"cep"`
	Complement            sql.NullString `json:"complement"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRowContext(ctx, updateDriver,
		arg.ID,
		arg.UserID,
		arg.BirthDate,
		arg.LicenseCategory,
		arg.LicenseExpirationDate,
		arg.State,
		arg.City,
		arg.Neighborhood,
		arg.Street,
		arg.StreetNumber,
		arg.Phone,
		arg.Cep,
		arg.Complement,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BirthDate,
		&i.Cpf,
		&i.LicenseNumber,
		&i.LicenseCategory,
		&i.LicenseExpirationDate,
		&i.State,
		&i.City,
		&i.Neighborhood,
		&i.Street,
		&i.StreetNumber,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Cep,
		&i.Complement,
	)
	return i, err
}
