// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: favorite_route.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createFavoriteRoute = `-- name: CreateFavoriteRoute :one
INSERT INTO public.favorite_route
(id, id_user, origin, destination, waypoints, response, created_who, created_at)
VALUES(nextval('favorite_route_id_seq'::regclass), $1, $2, $3, $4, $5, $6, now())
    RETURNING id, id_user, origin, destination, waypoints, response, created_who, created_at
`

type CreateFavoriteRouteParams struct {
	IDUser      int64           `json:"id_user"`
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Response    json.RawMessage `json:"response"`
	CreatedWho  string          `json:"created_who"`
}

func (q *Queries) CreateFavoriteRoute(ctx context.Context, arg CreateFavoriteRouteParams) (FavoriteRoute, error) {
	row := q.db.QueryRowContext(ctx, createFavoriteRoute,
		arg.IDUser,
		arg.Origin,
		arg.Destination,
		arg.Waypoints,
		arg.Response,
		arg.CreatedWho,
	)
	var i FavoriteRoute
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.Origin,
		&i.Destination,
		&i.Waypoints,
		&i.Response,
		&i.CreatedWho,
		&i.CreatedAt,
	)
	return i, err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE
FROM public.favorite_route
WHERE id = $1 AND
    id_user = $2
`

type RemoveFavoriteParams struct {
	ID     int64 `json:"id"`
	IDUser int64 `json:"id_user"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.ID, arg.IDUser)
	return err
}
