// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geo_coding.sql

package db

import (
	"context"
)

const consultUniqueCEP = `-- name: ConsultUniqueCEP :one
SELECT id, street_id, number, complement, cep, lat, lon, street_name, neighborhood_name, neighborhood_lat, neighborhood_lon, city_name, city_lat, city_lon, state_uf, state_lat, state_lon FROM unique_ceps WHERE cep = $1::varchar
`

func (q *Queries) ConsultUniqueCEP(ctx context.Context, dollar_1 string) (UniqueCep, error) {
	row := q.db.QueryRowContext(ctx, consultUniqueCEP, dollar_1)
	var i UniqueCep
	err := row.Scan(
		&i.ID,
		&i.StreetID,
		&i.Number,
		&i.Complement,
		&i.Cep,
		&i.Lat,
		&i.Lon,
		&i.StreetName,
		&i.NeighborhoodName,
		&i.NeighborhoodLat,
		&i.NeighborhoodLon,
		&i.CityName,
		&i.CityLat,
		&i.CityLon,
		&i.StateUf,
		&i.StateLat,
		&i.StateLon,
	)
	return i, err
}
