// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: login.sql

package db

import (
	"context"
	"database/sql"
)

const login = `-- name: Login :one
SELECT
    id, name, email, password, created_at, updated_at, profile_id, document, state, city, neighborhood, street, street_number, phone, google_id, profile_picture, status
FROM
    users
WHERE
    email = $1 and
    google_id = $2 and
    status = true
`

type LoginParams struct {
	Email    string         `json:"email"`
	GoogleID sql.NullString `json:"google_id"`
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, login, arg.Email, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.Document,
		&i.State,
		&i.City,
		&i.Neighborhood,
		&i.Street,
		&i.StreetNumber,
		&i.Phone,
		&i.GoogleID,
		&i.ProfilePicture,
		&i.Status,
	)
	return i, err
}
