// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Announcement struct {
	ID                 int64        `json:"id"`
	Destination        string       `json:"destination"`
	Origin             string       `json:"origin"`
	DestinationLat     string       `json:"destination_lat"`
	DestinationLng     string       `json:"destination_lng"`
	OriginLat          string       `json:"origin_lat"`
	OriginLng          string       `json:"origin_lng"`
	Description        string       `json:"description"`
	CargoDescription   string       `json:"cargo_description"`
	PaymentDescription string       `json:"payment_description"`
	DeliveryDate       time.Time    `json:"delivery_date"`
	PickupDate         time.Time    `json:"pickup_date"`
	DeadlineDate       time.Time    `json:"deadline_date"`
	Price              string       `json:"price"`
	Vehicle            string       `json:"vehicle"`
	BodyType           string       `json:"body_type"`
	Kilometers         string       `json:"kilometers"`
	CargoNature        string       `json:"cargo_nature"`
	CargoType          string       `json:"cargo_type"`
	CargoWeight        string       `json:"cargo_weight"`
	Tracking           bool         `json:"tracking"`
	RequiresTarp       bool         `json:"requires_tarp"`
	Status             bool         `json:"status"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type Balanca struct {
	ID             int64  `json:"id"`
	Concessionaria string `json:"concessionaria"`
	Km             string `json:"km"`
	Lat            string `json:"lat"`
	Lng            string `json:"lng"`
	Nome           string `json:"nome"`
	Rodovia        string `json:"rodovia"`
	Sentido        string `json:"sentido"`
	Uf             string `json:"uf"`
}

type Driver struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	BirthDate             time.Time      `json:"birth_date"`
	Cpf                   string         `json:"cpf"`
	LicenseNumber         string         `json:"license_number"`
	LicenseCategory       string         `json:"license_category"`
	LicenseExpirationDate time.Time      `json:"license_expiration_date"`
	State                 sql.NullString `json:"state"`
	City                  sql.NullString `json:"city"`
	Neighborhood          sql.NullString `json:"neighborhood"`
	Street                sql.NullString `json:"street"`
	StreetNumber          sql.NullString `json:"street_number"`
	Phone                 string         `json:"phone"`
	Status                bool           `json:"status"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type FavoriteRoute struct {
	ID          int64           `json:"id"`
	IDUser      int64           `json:"id_user"`
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Response    json.RawMessage `json:"response"`
	CreatedWho  string          `json:"created_who"`
	CreatedAt   time.Time       `json:"created_at"`
}

type FreightLoad struct {
	TypeOfLoad  sql.NullString `json:"type_of_load"`
	TwoAxes     sql.NullString `json:"two_axes"`
	ThreeAxes   sql.NullString `json:"three_axes"`
	FourAxes    sql.NullString `json:"four_axes"`
	FiveAxes    sql.NullString `json:"five_axes"`
	SixAxes     sql.NullString `json:"six_axes"`
	SevenAxes   sql.NullString `json:"seven_axes"`
	NineAxes    sql.NullString `json:"nine_axes"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

type GasStation struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Latitude      string `json:"latitude"`
	Longitude     string `json:"longitude"`
	AddressName   string `json:"address_name"`
	Municipio     string `json:"municipio"`
	SpecificPoint string `json:"specific_point"`
}

type Profile struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RouteHist struct {
	ID            int64           `json:"id"`
	IDUser        int64           `json:"id_user"`
	Origin        string          `json:"origin"`
	Destination   string          `json:"destination"`
	Waypoints     sql.NullString  `json:"waypoints"`
	Response      json.RawMessage `json:"response"`
	IsPublic      bool            `json:"is_public"`
	NumberRequest int64           `json:"number_request"`
	CreatedAt     time.Time       `json:"created_at"`
}

type SavedRoute struct {
	ID          int32           `json:"id"`
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Request     json.RawMessage `json:"request"`
	Response    json.RawMessage `json:"response"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	Favorite    sql.NullBool    `json:"favorite"`
	ExpiredAt   time.Time       `json:"expired_at"`
}

type TokenHist struct {
	ID            int64        `json:"id"`
	Ip            string       `json:"ip"`
	NumberRequest int64        `json:"number_request"`
	CreatedAt     time.Time    `json:"created_at"`
	ExpritedAt    time.Time    `json:"exprited_at"`
	Valid         sql.NullBool `json:"valid"`
}

type Toll struct {
	ID               int64          `json:"id"`
	Concessionaria   sql.NullString `json:"concessionaria"`
	PracaDePedagio   sql.NullString `json:"praca_de_pedagio"`
	AnoDoPnvSnv      sql.NullInt32  `json:"ano_do_pnv_snv"`
	Rodovia          sql.NullString `json:"rodovia"`
	Uf               sql.NullString `json:"uf"`
	KmM              sql.NullString `json:"km_m"`
	Municipio        sql.NullString `json:"municipio"`
	TipoPista        sql.NullString `json:"tipo_pista"`
	Sentido          sql.NullString `json:"sentido"`
	Situacao         sql.NullString `json:"situacao"`
	DataDaInativacao sql.NullString `json:"data_da_inativacao"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Tarifa           sql.NullString `json:"tarifa"`
	FreeFlow         sql.NullBool   `json:"free_flow"`
	PayFreeFlow      sql.NullString `json:"pay_free_flow"`
}

type TollTag struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	DealershipAccepts string `json:"dealership_accepts"`
}

type TractorUnit struct {
	ID              int64           `json:"id"`
	LicensePlate    string          `json:"license_plate"`
	DriverID        int64           `json:"driver_id"`
	UserID          int64           `json:"user_id"`
	Chassis         string          `json:"chassis"`
	Brand           string          `json:"brand"`
	Model           string          `json:"model"`
	ManufactureYear sql.NullInt32   `json:"manufacture_year"`
	EnginePower     sql.NullString  `json:"engine_power"`
	UnitType        sql.NullString  `json:"unit_type"`
	CanCouple       sql.NullBool    `json:"can_couple"`
	Height          sql.NullFloat64 `json:"height"`
	Status          bool            `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
}

type Trailer struct {
	ID           int64           `json:"id"`
	LicensePlate string          `json:"license_plate"`
	UserID       int64           `json:"user_id"`
	Chassis      string          `json:"chassis"`
	BodyType     sql.NullString  `json:"body_type"`
	LoadCapacity sql.NullFloat64 `json:"load_capacity"`
	Length       sql.NullFloat64 `json:"length"`
	Width        sql.NullFloat64 `json:"width"`
	Height       sql.NullFloat64 `json:"height"`
	Status       bool            `json:"status"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type Truck struct {
	ID            int64         `json:"id"`
	TractorUnitID int64         `json:"tractor_unit_id"`
	TrailerID     sql.NullInt64 `json:"trailer_id"`
	DriverID      int64         `json:"driver_id"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Password       sql.NullString `json:"password"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	ProfileID      sql.NullInt64  `json:"profile_id"`
	Document       sql.NullString `json:"document"`
	State          sql.NullString `json:"state"`
	City           sql.NullString `json:"city"`
	Neighborhood   sql.NullString `json:"neighborhood"`
	Street         sql.NullString `json:"street"`
	StreetNumber   sql.NullString `json:"street_number"`
	Phone          sql.NullString `json:"phone"`
	GoogleID       sql.NullString `json:"google_id"`
	ProfilePicture sql.NullString `json:"profile_picture"`
}
