// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type GasStation struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Latitude      string `json:"latitude"`
	Longitude     string `json:"longitude"`
	AddressName   string `json:"address_name"`
	Municipio     string `json:"municipio"`
	SpecificPoint string `json:"specific_point"`
}

type SavedRoute struct {
	ID          int32           `json:"id"`
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Response    json.RawMessage `json:"response"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	Favorite    sql.NullBool    `json:"favorite"`
}

type Toll struct {
	ID               int64          `json:"id"`
	CodigoAntt       sql.NullString `json:"codigo_antt"`
	Concessionaria   sql.NullString `json:"concessionaria"`
	PracaDePedagio   sql.NullString `json:"praca_de_pedagio"`
	AnoDoPnvSnv      sql.NullInt32  `json:"ano_do_pnv_snv"`
	Rodovia          sql.NullString `json:"rodovia"`
	Uf               sql.NullString `json:"uf"`
	KmM              sql.NullString `json:"km_m"`
	Municipio        sql.NullString `json:"municipio"`
	TipoPista        sql.NullString `json:"tipo_pista"`
	Sentido          sql.NullString `json:"sentido"`
	Situacao         sql.NullString `json:"situacao"`
	DataDaInativacao sql.NullString `json:"data_da_inativacao"`
	Latitude         sql.NullString `json:"latitude"`
	Longitude        sql.NullString `json:"longitude"`
	Tarifa           string         `json:"tarifa"`
	FreeFlow         sql.NullBool   `json:"free_flow"`
}

type TollTag struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	DealershipAccepts string `json:"dealership_accepts"`
}
