// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: offers.sql

package db

import (
	"context"
	"database/sql"
)

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers
(advertisement_id, price, interested_id)
VALUES
($1, $2, $3)
RETURNING id, advertisement_id, price, interested_id
`

type CreateOfferParams struct {
	AdvertisementID sql.NullInt64 `json:"advertisement_id"`
	Price           float64       `json:"price"`
	InterestedID    sql.NullInt64 `json:"interested_id"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer, arg.AdvertisementID, arg.Price, arg.InterestedID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.AdvertisementID,
		&i.Price,
		&i.InterestedID,
	)
	return i, err
}
