// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"
)

const getPlansById = `-- name: GetPlansById :one
SELECT id, name, price, duration
FROM public."plans"
WHERE id=$1
`

func (q *Queries) GetPlansById(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlansById, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Duration,
	)
	return i, err
}
