// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profiles.sql

package db

import (
	"context"
)

const getProfileById = `-- name: GetProfileById :one
SELECT id, name
FROM profiles
WHERE id=$1
`

func (q *Queries) GetProfileById(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileById, id)
	var i Profile
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
