// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: route_hist.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createRouteHist = `-- name: CreateRouteHist :one
INSERT INTO public.route_hist
(id, id_token_hist, origin, destination, waypoints, response, created_at)
VALUES(nextval('route_hist_id_seq'::regclass), $1, $2, $3, $4, $5, now())
    RETURNING id, id_token_hist, origin, destination, waypoints, response, created_at
`

type CreateRouteHistParams struct {
	IDTokenHist int64           `json:"id_token_hist"`
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Response    json.RawMessage `json:"response"`
}

func (q *Queries) CreateRouteHist(ctx context.Context, arg CreateRouteHistParams) (RouteHist, error) {
	row := q.db.QueryRowContext(ctx, createRouteHist,
		arg.IDTokenHist,
		arg.Origin,
		arg.Destination,
		arg.Waypoints,
		arg.Response,
	)
	var i RouteHist
	err := row.Scan(
		&i.ID,
		&i.IDTokenHist,
		&i.Origin,
		&i.Destination,
		&i.Waypoints,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}
