// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saved_routes.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createSavedRoutes = `-- name: CreateSavedRoutes :one
INSERT INTO public.saved_routes
(id, origin, destination, waypoints, request, response, created_at, expired_at)
VALUES(nextval('saved_routes_id_seq'::regclass), $1, $2, $3, $4, $5,now(), $6)
    RETURNING id, origin, destination, waypoints, request, response, created_at, updated_at, favorite, expired_at
`

type CreateSavedRoutesParams struct {
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Request     json.RawMessage `json:"request"`
	Response    json.RawMessage `json:"response"`
	ExpiredAt   time.Time       `json:"expired_at"`
}

func (q *Queries) CreateSavedRoutes(ctx context.Context, arg CreateSavedRoutesParams) (SavedRoute, error) {
	row := q.db.QueryRowContext(ctx, createSavedRoutes,
		arg.Origin,
		arg.Destination,
		arg.Waypoints,
		arg.Request,
		arg.Response,
		arg.ExpiredAt,
	)
	var i SavedRoute
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.Waypoints,
		&i.Request,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Favorite,
		&i.ExpiredAt,
	)
	return i, err
}

const getSavedRouteById = `-- name: GetSavedRouteById :one
SELECT id, origin, destination, waypoints, request, response, created_at, updated_at, favorite, expired_at
FROM public.saved_routes
WHERE ID = $1
`

func (q *Queries) GetSavedRouteById(ctx context.Context, id int32) (SavedRoute, error) {
	row := q.db.QueryRowContext(ctx, getSavedRouteById, id)
	var i SavedRoute
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.Waypoints,
		&i.Request,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Favorite,
		&i.ExpiredAt,
	)
	return i, err
}

const getSavedRoutes = `-- name: GetSavedRoutes :one
SELECT id, origin, destination, waypoints, request, response, created_at, updated_at, favorite, expired_at
FROM public.saved_routes
WHERE origin = $1 AND
      destination = $2 AND
      waypoints = $3 AND
      request = $4
`

type GetSavedRoutesParams struct {
	Origin      string          `json:"origin"`
	Destination string          `json:"destination"`
	Waypoints   sql.NullString  `json:"waypoints"`
	Request     json.RawMessage `json:"request"`
}

func (q *Queries) GetSavedRoutes(ctx context.Context, arg GetSavedRoutesParams) (SavedRoute, error) {
	row := q.db.QueryRowContext(ctx, getSavedRoutes,
		arg.Origin,
		arg.Destination,
		arg.Waypoints,
		arg.Request,
	)
	var i SavedRoute
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.Waypoints,
		&i.Request,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Favorite,
		&i.ExpiredAt,
	)
	return i, err
}
