// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: token_hist.sql

package db

import (
	"context"
	"time"
)

const createTokenHist = `-- name: CreateTokenHist :one
INSERT INTO public.token_hist
(id, ip, number_request, created_at, exprited_at, "valid")
VALUES(nextval('token_hist_id_seq'::regclass), $1, $2, now(), $3, true)
    RETURNING id, ip, number_request, created_at, exprited_at, valid
`

type CreateTokenHistParams struct {
	Ip            string    `json:"ip"`
	NumberRequest int64     `json:"number_request"`
	ExpritedAt    time.Time `json:"exprited_at"`
}

func (q *Queries) CreateTokenHist(ctx context.Context, arg CreateTokenHistParams) (TokenHist, error) {
	row := q.db.QueryRowContext(ctx, createTokenHist, arg.Ip, arg.NumberRequest, arg.ExpritedAt)
	var i TokenHist
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.NumberRequest,
		&i.CreatedAt,
		&i.ExpritedAt,
		&i.Valid,
	)
	return i, err
}
