// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token_hist.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTokenHist = `-- name: CreateTokenHist :one
INSERT INTO public.token_hist
(id, ip, number_request, created_at, exprited_at, "valid", token)
VALUES(nextval('token_hist_id_seq'::regclass), $1, $2, now(), $3, true, $4)
    RETURNING id, ip, number_request, created_at, exprited_at, valid, token
`

type CreateTokenHistParams struct {
	Ip            string    `json:"ip"`
	NumberRequest int64     `json:"number_request"`
	ExpritedAt    time.Time `json:"exprited_at"`
	Token         string    `json:"token"`
}

func (q *Queries) CreateTokenHist(ctx context.Context, arg CreateTokenHistParams) (TokenHist, error) {
	row := q.db.QueryRowContext(ctx, createTokenHist,
		arg.Ip,
		arg.NumberRequest,
		arg.ExpritedAt,
		arg.Token,
	)
	var i TokenHist
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.NumberRequest,
		&i.CreatedAt,
		&i.ExpritedAt,
		&i.Valid,
		&i.Token,
	)
	return i, err
}

const getTokenHist = `-- name: GetTokenHist :one
SELECT id, ip, number_request, created_at, exprited_at, valid, token
FROM public.token_hist
WHERE ip=$1
`

func (q *Queries) GetTokenHist(ctx context.Context, ip string) (TokenHist, error) {
	row := q.db.QueryRowContext(ctx, getTokenHist, ip)
	var i TokenHist
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.NumberRequest,
		&i.CreatedAt,
		&i.ExpritedAt,
		&i.Valid,
		&i.Token,
	)
	return i, err
}

const getTokenHistExist = `-- name: GetTokenHistExist :one
SELECT EXISTS (
    SELECT 1
    FROM public.token_hist
    WHERE ip = $1
)
`

func (q *Queries) GetTokenHistExist(ctx context.Context, ip string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getTokenHistExist, ip)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateNumberOfRequest = `-- name: UpdateNumberOfRequest :exec
UPDATE public.route_hist
SET number_request = $1
WHERE id = $2
`

type UpdateNumberOfRequestParams struct {
	NumberRequest int64 `json:"number_request"`
	ID            int64 `json:"id"`
}

func (q *Queries) UpdateNumberOfRequest(ctx context.Context, arg UpdateNumberOfRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateNumberOfRequest, arg.NumberRequest, arg.ID)
	return err
}

const updateTokenHist = `-- name: UpdateTokenHist :one
UPDATE public.token_hist
SET number_request = $2,
    exprited_at = $3,
    token = $4,
    created_at = now()
WHERE id = $1
    RETURNING id, ip, number_request, valid, exprited_at, token
`

type UpdateTokenHistParams struct {
	ID            int64     `json:"id"`
	NumberRequest int64     `json:"number_request"`
	ExpritedAt    time.Time `json:"exprited_at"`
	Token         string    `json:"token"`
}

type UpdateTokenHistRow struct {
	ID            int64        `json:"id"`
	Ip            string       `json:"ip"`
	NumberRequest int64        `json:"number_request"`
	Valid         sql.NullBool `json:"valid"`
	ExpritedAt    time.Time    `json:"exprited_at"`
	Token         string       `json:"token"`
}

func (q *Queries) UpdateTokenHist(ctx context.Context, arg UpdateTokenHistParams) (UpdateTokenHistRow, error) {
	row := q.db.QueryRowContext(ctx, updateTokenHist,
		arg.ID,
		arg.NumberRequest,
		arg.ExpritedAt,
		arg.Token,
	)
	var i UpdateTokenHistRow
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.NumberRequest,
		&i.Valid,
		&i.ExpritedAt,
		&i.Token,
	)
	return i, err
}
