// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: toll_tags.sql

package db

import (
	"context"
)

const getTollTags = `-- name: GetTollTags :many
SELECT id, name, dealership_accepts
FROM public.toll_tags
`

func (q *Queries) GetTollTags(ctx context.Context) ([]TollTag, error) {
	rows, err := q.db.QueryContext(ctx, getTollTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TollTag
	for rows.Next() {
		var i TollTag
		if err := rows.Scan(&i.ID, &i.Name, &i.DealershipAccepts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
