// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: tools.sql

package db

import (
	"context"
)

const getTollsByLonAndLat = `-- name: GetTollsByLonAndLat :many
SELECT id, concessionaria, praca_de_pedagio, ano_do_pnv_snv, rodovia, uf, km_m, municipio, tipo_pista, sentido, situacao, data_da_inativacao, latitude, longitude, tarifa, free_flow, pay_free_flow
FROM public.tolls
`

func (q *Queries) GetTollsByLonAndLat(ctx context.Context) ([]Toll, error) {
	rows, err := q.db.QueryContext(ctx, getTollsByLonAndLat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Toll
	for rows.Next() {
		var i Toll
		if err := rows.Scan(
			&i.ID,
			&i.Concessionaria,
			&i.PracaDePedagio,
			&i.AnoDoPnvSnv,
			&i.Rodovia,
			&i.Uf,
			&i.KmM,
			&i.Municipio,
			&i.TipoPista,
			&i.Sentido,
			&i.Situacao,
			&i.DataDaInativacao,
			&i.Latitude,
			&i.Longitude,
			&i.Tarifa,
			&i.FreeFlow,
			&i.PayFreeFlow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
