// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: trailer.sql

package db

import (
	"context"
	"database/sql"
)

const createTrailer = `-- name: CreateTrailer :one
INSERT INTO public.trailer
(id, license_plate, user_id, chassis, body_type, load_capacity, length, width, height, axles, status, created_at)
VALUES(nextval('trailer_id_seq'::regclass), $1, $2, $3, $4, $5, $6, $7, $8, $9,  true, now())
    RETURNING id, license_plate, user_id, chassis, body_type, load_capacity, length, width, height, axles, status, created_at, updated_at
`

type CreateTrailerParams struct {
	LicensePlate string          `json:"license_plate"`
	UserID       int64           `json:"user_id"`
	Chassis      string          `json:"chassis"`
	BodyType     sql.NullString  `json:"body_type"`
	LoadCapacity sql.NullFloat64 `json:"load_capacity"`
	Length       sql.NullFloat64 `json:"length"`
	Width        sql.NullFloat64 `json:"width"`
	Height       sql.NullFloat64 `json:"height"`
	Axles        int64           `json:"axles"`
}

func (q *Queries) CreateTrailer(ctx context.Context, arg CreateTrailerParams) (Trailer, error) {
	row := q.db.QueryRowContext(ctx, createTrailer,
		arg.LicensePlate,
		arg.UserID,
		arg.Chassis,
		arg.BodyType,
		arg.LoadCapacity,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Axles,
	)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.UserID,
		&i.Chassis,
		&i.BodyType,
		&i.LoadCapacity,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Axles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrailer = `-- name: DeleteTrailer :exec
UPDATE public.trailer
SET status=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteTrailer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrailer, id)
	return err
}

const getTrailerById = `-- name: GetTrailerById :one
SELECT id, license_plate, user_id, chassis, body_type, load_capacity, length, width, height, axles, status, created_at, updated_at
FROM public.trailer
WHERE id=$1
`

func (q *Queries) GetTrailerById(ctx context.Context, id int64) (Trailer, error) {
	row := q.db.QueryRowContext(ctx, getTrailerById, id)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.UserID,
		&i.Chassis,
		&i.BodyType,
		&i.LoadCapacity,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Axles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrailer = `-- name: UpdateTrailer :one
UPDATE public.trailer
SET license_plate=$1, chassis=$2, body_type=$3, load_capacity=$4, length=$5, width=$6, height=$7, axles=$8, user_id=$9, updated_at=now()
WHERE id=$10
    RETURNING id, license_plate, user_id, chassis, body_type, load_capacity, length, width, height, axles, status, created_at, updated_at
`

type UpdateTrailerParams struct {
	LicensePlate string          `json:"license_plate"`
	Chassis      string          `json:"chassis"`
	BodyType     sql.NullString  `json:"body_type"`
	LoadCapacity sql.NullFloat64 `json:"load_capacity"`
	Length       sql.NullFloat64 `json:"length"`
	Width        sql.NullFloat64 `json:"width"`
	Height       sql.NullFloat64 `json:"height"`
	Axles        int64           `json:"axles"`
	UserID       int64           `json:"user_id"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdateTrailer(ctx context.Context, arg UpdateTrailerParams) (Trailer, error) {
	row := q.db.QueryRowContext(ctx, updateTrailer,
		arg.LicensePlate,
		arg.Chassis,
		arg.BodyType,
		arg.LoadCapacity,
		arg.Length,
		arg.Width,
		arg.Height,
		arg.Axles,
		arg.UserID,
		arg.ID,
	)
	var i Trailer
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.UserID,
		&i.Chassis,
		&i.BodyType,
		&i.LoadCapacity,
		&i.Length,
		&i.Width,
		&i.Height,
		&i.Axles,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
