// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_tokens_hist.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createUserTokenHist = `-- name: CreateUserTokenHist :one
INSERT INTO user_tokens_hist (user_id, token, payload, expired_at, origin)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, token, payload, expired_at, origin, created_at
`

type CreateUserTokenHistParams struct {
	UserID    int64           `json:"user_id"`
	Token     string          `json:"token"`
	Payload   json.RawMessage `json:"payload"`
	ExpiredAt time.Time       `json:"expired_at"`
	Origin    string          `json:"origin"`
}

func (q *Queries) CreateUserTokenHist(ctx context.Context, arg CreateUserTokenHistParams) (UserTokensHist, error) {
	row := q.db.QueryRowContext(ctx, createUserTokenHist,
		arg.UserID,
		arg.Token,
		arg.Payload,
		arg.ExpiredAt,
		arg.Origin,
	)
	var i UserTokensHist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Payload,
		&i.ExpiredAt,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}
