// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_request_hist.sql

package db

import (
	"context"
	"database/sql"
)

const createUserRequestHist = `-- name: CreateUserRequestHist :one
INSERT INTO user_request_hist (user_id, token, endpoint, method, status_code, execution_time_ms)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, token, endpoint, method, status_code, execution_time_ms, created_at
`

type CreateUserRequestHistParams struct {
	UserID          sql.NullInt64 `json:"user_id"`
	Token           string        `json:"token"`
	Endpoint        string        `json:"endpoint"`
	Method          string        `json:"method"`
	StatusCode      int32         `json:"status_code"`
	ExecutionTimeMs int32         `json:"execution_time_ms"`
}

func (q *Queries) CreateUserRequestHist(ctx context.Context, arg CreateUserRequestHistParams) (UserRequestHist, error) {
	row := q.db.QueryRowContext(ctx, createUserRequestHist,
		arg.UserID,
		arg.Token,
		arg.Endpoint,
		arg.Method,
		arg.StatusCode,
		arg.ExecutionTimeMs,
	)
	var i UserRequestHist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Endpoint,
		&i.Method,
		&i.StatusCode,
		&i.ExecutionTimeMs,
		&i.CreatedAt,
	)
	return i, err
}
