name: "[DEPLOY] Docker Build and Deploy"

on:
  push:
    branches:
      - homolog-test

jobs:
  deploy-to-ec2-homolog-test:
    name: Deploy to EC2 (homolog-test)
    runs-on: ubuntu-latest
    if: github.ref_name == 'homolog-test'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conectar ao EC2 e Atualizar o Container Homolog Test
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_PUBLIC_IP_SP }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY_SP }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            echo "Acessando diretório do projeto..."
            cd /home/ubuntu/projects/geolocation
          
            echo "Atualizando código..."
            git fetch --all
            git checkout homolog-test
            git pull origin homolog-test
          
            echo "Construindo imagem Docker..."
            docker build -t go-geolocation .
          
            echo "Parando container antigo..."
            docker ps -q -f name=go-geolocation-container && docker stop go-geolocation-container || true
            docker ps -a -q -f name=go-geolocation-container && docker rm go-geolocation-container || true
          
            echo "Executando novo container..."
            docker run -d -p 3000:8080 --env-file .env --name go-geolocation-container go-geolocation
          
            echo "Limpando imagens antigas..."
            docker image prune -f
          
            echo "Deploy concluído!"
          EOF
          
          rm -f private_key.pem